apiVersion: v2
name: confluence
description: A chart for installing Confluence Data Center on Kubernetes
type: application
version: 2.0.3-bb.1
appVersion: 10.0.2
kubeVersion: ">=1.21.x-0"
keywords:
  - Confluence
  - Confluence Server
  - Confluence Data Center
  - Confluence DC
  - Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/confluence.svg
sources:
  - https://github.com/atlassian/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-confluence-server/
deprecated: false
dependencies:
  - name: common
    version: 1.2.7
    repository: https://atlassian.github.io/data-center-helm-charts
  - name: gluon
    version: 0.8.0
    repository: oci://registry1.dso.mil/bigbang
  - name: postgresql
    version: 13.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.install
  - name: opensearch
    version: 3.2.1
    repository: https://opensearch-project.github.io/helm-charts
    condition: opensearch.enabled
annotations:
  bigbang.dev/maintenanceTrack: bb_maintained
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |-
    - "StatefulSet PVC auto deletion (#736)"
    - "Add optional postStart hook (#735)"
    - "Add Openshift analytics (#763)"
    - "Update appVersions for DC apps (#765)"
    - "Removed unused Confluence shared home volume from Synchrony volume. (#764)"
    - "OpenShift Support (#752)"
    - "Use testPods values for test images and container resources (#761)"
    - "Relabel instance name on jmx service monitor (#757)"
    - "Added pvc retention policy to Bitbucket Mesh StatefulSet (#755)"
    - "Include shared home for synchrony when additional libs are defined (#779)"
    - "Get rid of server repo references (#777)"
    - "Make cacerts writable for user and group (#790)"
    - "Optionally deploy OpenSearch Helm Chart With Confluence (#788)"
    - "Update appVersions for DC apps (#803)"
    - "Set atlassian.logging.cloud.enabled system property to false if a custom FluentD config is used (#796)"
    - "Update appVersions for DC apps (#869)"
    - "Update common dependency version (#878)"
    - "Create a dedicated Synchrony ingress (#883)"
    - "Update appVersions for DC apps (#905)"
    - "Updated pod labels for all products (#901)"
    - "Fix shutdown with jmx javaagent enabled (#899)"
    - "Unset IDs for all the Grafana dashboards (#889)"
  bigbang.dev/applicationVersions: |
    - Confluence: 10.0.2
  helm.sh/images: |
    - name: confluence-node
      image: registry1.dso.mil/ironbank/atlassian/confluence-data-center/confluence-node-lts:9.2.7 
    - name: fluentd-kubernetes-daemonset
      condition: fluentd.enabled
      image: fluent/fluentd-kubernetes-daemonset:v1.11.5-debian-elasticsearch7-1.2
    - name: base
      image: registry1.dso.mil/ironbank/big-bang/base:2.1.0
    - name: postgres
      condition: postgresql.install
      image: registry1.dso.mil/ironbank/opensource/postgres/postgresql:17.6
