apiVersion: v2
name: confluence
description: A chart for installing Confluence DC on Kubernetes
type: application
version: 0.1.0
appVersion: 7.9.0-jdk11
kubeVersion: ">=1.17.x-0"
keywords:
  - Confluence
  - Confluence Server
  - Confluence Data Center
  - Atlassian
home: https://github.com/atlassian-labs/data-center-helm-charts
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
deprecated: false
