apiVersion: v2
name: confluence
description: A chart for installing Confluence Data Center on Kubernetes
type: application
version: 1.16.6-bb.0
appVersion: 8.6.1
kubeVersion: ">=1.21.x-0"
keywords:
- Confluence
- Confluence Server
- Confluence Data Center
- Confluence DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/confluence.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-confluence-server/
deprecated: false
dependencies:
  - name: common
    version: 1.2.5
    repository: https://atlassian.github.io/data-center-helm-charts
  - name: gluon
    version: "0.4.1"
    repository: "oci://registry1.dso.mil/bigbang"
  - name: postgresql
    version: 13.1.5 
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.install
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |-
    - "JMX container resources (#707)"
  bigbang.dev/applicationVersions: |
    - Confluence: 8.6.0
  helm.sh/images: |
    - name: confluence-node
      image: registry1.dso.mil/ironbank/atlassian/confluence-data-center/confluence-node:8.6.1
    - name: fluentd-kubernetes-daemonset
      condition: fluentd.enabled
      image: fluent/fluentd-kubernetes-daemonset:v1.11.5-debian-elasticsearch7-1.2
    - name: base
      image: registry1.dso.mil/ironbank/big-bang/base:2.0.0
    - name: postgres
      condition: postgresql.install
      image: registry1.dso.mil/ironbank/opensource/postgres/postgresql:15.4