{{- if and .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-minio-operator-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          {{- if .Values.networkPolicies.istioNamespaceSelector }}
            app.kubernetes.io/name: {{ .Values.networkPolicies.istioNamespaceSelector.ingress }}
            {{- else }}
            app.kubernetes.io/name: "istio-controlplane"
            {{- end }}
    ports:
    - port: 9000
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "minio.labels" . | nindent 6 }}
  policyTypes:
  - Ingress
{{- end }}
