{{- if and .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-minio-operator-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "minio.labels" . | nindent 6 }}  
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            {{- if .Values.networkPolicies.istioNamespaceSelector }}
            app.kubernetes.io/name: {{ .Values.networkPolicies.istioNamespaceSelector.egress }}
            {{- else }}
            app.kubernetes.io/name: "istio-controlplane"
            {{- end }}
      ports:
      - port: 4222
        protocol: TCP
{{- end }}
