apiVersion: v1
apiVersion: v1
kind: Service
metadata:
  name: {{ include "confluence.fullname" . }}
  labels:
    {{- include "confluence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.confluence.service.type }}
  ports:
    - port: {{ .Values.confluence.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.confluence.ports.hazelcast }}
      targetPort: hazelcast
      protocol: TCP
      name: hazelcast
    - port: {{ .Values.confluence.ports.intconnector }}
      targetPort: intconnector
      protocol: TCP
      name: intconnector
    - port: {{ .Values.confluence.ports.intersvc }}
      targetPort: intersvc
      protocol: TCP
      name: intersvc
    - port: {{ .Values.confluence.ports.synchrony }}
      targetPort: synchrony
      protocol: TCP
      name: synchrony
  selector:
    {{- include "confluence.selectorLabels" . | nindent 4 }}
