apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "confluence.fullname" . }}
  labels:
    {{- include "confluence.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "confluence.fullname" . }}
  selector:
    matchLabels:
      {{- include "confluence.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "confluence.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "confluence.serviceAccountName" . }}
      terminationGracePeriodSeconds: 1
      securityContext:
        # This is intended to ensure that the shared-home volume is group-writeable by the GID used by the Cnfluence container.
        # However, this doesn't appear to work for NFS volumes due to a K8s bug: https://github.com/kubernetes/examples/issues/260
        fsGroup: {{ .Values.confluence.gid }}
      {{- with .Values.additionalInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: confluence
          image: {{ include "confluence.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.confluence.ports.http }}
              protocol: TCP
            - name: hazelcast
              containerPort: {{ .Values.confluence.ports.hazelcast }}
              protocol: TCP
          readinessProbe:
            httpGet:
              port: {{ .Values.confluence.ports.http }}
              path: /status
            initialDelaySeconds: {{ .Values.confluence.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.confluence.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.confluence.readinessProbe.failureThreshold }}
          {{- with .Values.confluence.resources.container }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: local-home
              mountPath: {{ .Values.volumes.localHome.mountPath | quote }}
            - name: shared-home
              mountPath: {{ .Values.volumes.sharedHome.mountPath | quote }}
              {{- if .Values.volumes.sharedHome.subPath }}
              subPath: {{ .Values.volumes.sharedHome.subPath | quote }}
              {{- end }}
            {{- with .Values.confluence.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- include "confluence.additionalLibraries" . | nindent 12 }}
            {{- include "confluence.additionalBundledPlugins" . | nindent 12 }}
          env:
            {{ if .Values.ingress.https }}
            - name: ATL_TOMCAT_SCHEME
              value: "https"
            - name: ATL_TOMCAT_SECURE
              value: "true"
            {{ end }}
            - name: ATL_PRODUCT_HOME_SHARED
              value: {{ .Values.volumes.sharedHome.mountPath | quote }}
            - name: JVM_SUPPORT_RECOMMENDED_ARGS
              valueFrom:
                configMapKeyRef:
                  key: additional_jvm_args
                  name: {{ include "confluence.fullname" . }}-jvm-config
            {{- include "confluence.clusteringEnvVars" . | nindent 12 }}
            {{- include "confluence.databaseEnvVars" . | nindent 12 }}
            {{ with .Values.confluence.license.secretName }}
            - name: ATL_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: {{ $.Values.confluence.license.secretKey }}
            {{ end }}
            - name: JVM_MINIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: min_heap
                  name: {{ include "confluence.fullname" . }}-jvm-config
            - name: JVM_MAXIMUM_MEMORY
              valueFrom:
                configMapKeyRef:
                  key: max_heap
                  name: {{ include "confluence.fullname" . }}-jvm-config
            - name: JVM_RESERVED_CODE_CACHE_SIZE
              valueFrom:
                configMapKeyRef:
                  key: reserved_code_cache
                  name: {{ include "confluence.fullname" . }}-jvm-config
            {{- with .Values.confluence.additionalEnvironmentVariables }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.additionalContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{ include "confluence.volumes" . | nindent 8 }}
  {{ include "confluence.volumeClaimTemplates" . | nindent 2 }}