{{ if and .Values.synchrony.enabled (not .Values.synchrony.managed) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "synchrony.fullname" . }}
  labels:
    {{- include "synchrony.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "synchrony.fullname" . }}
  selector:
    matchLabels:
      {{- include "synchrony.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "synchrony.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "confluence.serviceAccountName" . }}
      terminationGracePeriodSeconds: 1
      containers:
        - name: synchrony
          image: {{ include "confluence.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/scripts/start-synchrony.sh"]
          volumeMounts:
            - mountPath: /scripts
              name: entrypoint-script
          ports:
            - name: http-synch
              containerPort: {{ .Values.synchrony.ports.http }}
              protocol: TCP
            - name: hazelcast-synch
              containerPort: {{ .Values.synchrony.ports.hazelcast }}
              protocol: TCP
          readinessProbe:
            httpGet:
              port: {{ .Values.synchrony.ports.http }}
              path: /heartbeat
            initialDelaySeconds: {{ .Values.synchrony.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.synchrony.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.synchrony.readinessProbe.failureThreshold }}
          env:
            - name: SYNCHRONY_BIND
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SYNCHRONY_SERVICE_URL
              value: {{ .Values.synchrony.ingressUrl | quote }}
            {{- include "synchrony.databaseEnvVars" . | nindent 12 }}
            {{- include "synchrony.clusteringEnvVars" . | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: entrypoint-script
          configMap:
            name: {{ include "synchrony.fullname" . }}-entrypoint
            defaultMode: 0744
{{ end }}