{{- if and .Values.upstream.confluence.clustering.enabled .Values.upstream.serviceAccount.clusterRoleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "confluence.clusterRoleBindingName" . }}
  labels:
  {{- include "common.labels.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "confluence.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "confluence.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
