{{- if .Values.rbac.enabled }}
# https://github.com/Praqma/ask/blob/master/confluence/templates/clusterrolebindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ include "confluence-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}