{{- if .Values.database.credentials.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName | default (printf "%s-db-credentials" (include "common.names.fullname" .)) }}
type: Opaque
data:
  {{ .Values.database.credentials.usernameSecretKey | default "username" }}: {{ tpl (.Values.database.user | quote) . | b64enc }}
  {{ .Values.database.credentials.passwordSecretKey | default "password" }}: {{ tpl (.Values.database.password | quote) . | b64enc }}
{{- end -}}
