{{- $db := .Values.database | default dict -}}
{{- $creds := $db.credentials | default dict -}}
{{- if and (not $creds.secretName) ($db.user) ($db.password) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName | default (printf "%s-db-credentials" (include "common.names.fullname" .)) }}
type: Opaque
data:
  {{ default "username" $creds.usernameSecretKey }}: {{ tpl (toString $db.user) . | b64enc }}
  {{ default "password" $creds.passwordSecretKey }}: {{ tpl (toString $db.password) . | b64enc }}
{{- end }}