{{- if and .Values.istio.enabled .Values.synchrony.enabled (not .Values.synchrony.managed) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "synchrony.fullname" . }}
  labels:
    {{- include "synchrony.labels" . | nindent 4 }}
spec:
  hosts:
  - synchrony.{{ .Values.hostname }}
  gateways:
  - istio-system/main
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "synchrony.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.synchrony.service.port }}
{{- end }}