{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "confluence.fullname" . }}
  labels:
    {{- include "confluence.labels" . | nindent 4 }}
spec:
  hosts:
  - confluence.{{ .Values.hostname }}
  gateways:
  - {{ .Values.istio.gateway }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "confluence.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.confluence.service.port }}
      headers:
        request:
          remove:
            - x-b3-sampled
          add:
            x-b3-sampled: '0'
{{- end }}
