{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - confluence.{{ .Values.hostname }}
  gateways:
  - main.istio-system.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "confluence-server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8090
      headers:
        request:
          remove:
            - x-b3-sampled
          add:
            x-b3-sampled: '0'
{{- end }}