{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "confluence.fullname" . }}
  labels:
    {{- include "confluence.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ .Values.hostnamePrefix }}.{{ .Values.hostname }}
  gateways:
  {{- range .Values.istio.gateways }}
    - {{ . }}
  {{- end }}
  http:
  {{- if .Values.synchrony.enabled }}
  - match:
    - uri:
        prefix: /synchrony
    route:
    - destination:
        host: {{ include "synchrony.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.synchrony.service.port }}
      headers:
        request:
          remove:
            - x-b3-sampled
          add:
            x-b3-sampled: '0'
  {{- end }}
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "confluence.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.confluence.service.port }}
      headers:
        request:
          remove:
            - x-b3-sampled
          add:
            x-b3-sampled: '0'
{{- end }}
