apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence-efs-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  claimRef:
    namespace: confluence
    name: confluence-shared
  csi:
    driver: efs.csi.aws.com
    volumeHandle: 
